/**
 * ESON object with parse and stringify methods
 * Suggested by @ma27inranma
 * https://github.com/ma27inranma/ESONparser
 * 
 * Generated by GitHub Copilot 
 */
namespace ESON {
    /**
     * Parse a ESON string into a JavaScript object.
     * @param {string} input - The ESON string, e.g. {key=value,arr=[1,2,3]}
     * @returns {object} - Parsed object
     */
    export function parse(input: string): Record<string, any> {
        // Trim outer braces if present
        let trimmed = input.trim();
        if (trimmed.startsWith("{") && trimmed.endsWith("}")) {
            trimmed = trimmed.slice(1, -1);
        }

        // Top-level parse function (handles key=value pairs)
        return parseObject(trimmed);
    }

    /**
     * Stringify a JavaScript object into a ESON string.
     * @param {object|Array<any>} obj - The object to stringify
     * @returns {string} - ESON formatted string
     */
    export function stringify(obj: object | Array<any>): string {
        if (Array.isArray(obj)) {
            return stringifyArray(obj);
        }
        if (obj !== null && typeof obj === "object") {
            const entries = Object.entries(obj).map(([key, value]) => {
                return `${key}=${stringifyValue(value)}`;
            });
            return `{${entries.join(",")}}`;
        }
        return stringifyValue(obj);
    }
}

/**
 * Parses an ESON object content (key=value pairs).
 * @param {string} str - The string without outer braces.
 * @returns {Object}
 */
function parseObject(str: string): Record<string, any> {
    const result: Record<string, any> = {};
    if (!str.trim()) {
        return result;
    }

    // Split by commas at the top level
    const pairs = splitTopLevel(str, ",");

    // For each "key=value" pair
    pairs.forEach((pair) => {
        const eqPos = pair.indexOf("=");
        if (eqPos < 0) {
            return;
        }
        const key = pair.slice(0, eqPos).trim();
        const valueStr = pair.slice(eqPos + 1).trim();
        result[key] = parseValue(valueStr);
    });
    return result;
}

/**
 * Parses a single value string:
 * - ESON object { ... }
 * - Array [ ... ]
 * - String in single quotes
 * - Booleans, null, or number
 * @param {string} valueStr
 * @returns {any}
 */
function parseValue(valueStr: string): any {
    // Check for nested object
    if (valueStr.startsWith("{") && valueStr.endsWith("}")) {
        return ESON.parse(valueStr);
    }
    // Check for array
    if (valueStr.startsWith("[") && valueStr.endsWith("]")) {
        return parseArray(valueStr);
    }
    // Check for single-quoted strings
    if ((valueStr.startsWith("'") && valueStr.endsWith("'")) || (valueStr.startsWith('"') && valueStr.endsWith('"'))) {
        return valueStr.slice(1, -1);
    }
    // Check for booleans, null, or numeric
    if (valueStr === "true") return true;
    if (valueStr === "false") return false;
    if (valueStr === "null") return null;
    if (!isNaN(Number(valueStr))) return Number(valueStr);

    // Otherwise treat as string
    return valueStr;
}

/**
 * Parses an ESON array string [1,2,3].
 * @param {string} arrStr
 * @returns {Array}
 */
function parseArray(arrStr: string): any[] {
    // Remove outer brackets
    let content = arrStr.slice(1, -1).trim();
    if (!content) {
        return [];
    }
    const items = splitTopLevel(content, ",");
    return items.map((item) => parseValue(item.trim()));
}

/**
 * Split a string by a delimiter at top level (matching braces/quotes).
 * Modified to allow unescaped single quotes inside a string.
 * @param {string} input
 * @param {string} delimiter
 * @returns {string[]}
 */
function splitTopLevel(input: string, delimiter: string): string[] {
    const result: string[] = [];
    let depthCurly = 0;
    let depthSquare = 0;
    let inQuote = false;
    let quoteChar = "";
    let startIndex = 0;

    for (let i = 0; i < input.length; i++) {
        const ch = input[i];
        if (inQuote) {
            if (ch === quoteChar) {
                const next = input[i + 1];
                if (i + 1 === input.length || next === delimiter || next === "}" || next === "]" || /\s/.test(next)) {
                    inQuote = false;
                }
            }
            continue;
        } else {
            if (ch === "'" || ch === '"') {
                inQuote = true;
                quoteChar = ch;
            } else if (ch === "{") {
                depthCurly++;
            } else if (ch === "}") {
                depthCurly--;
            } else if (ch === "[") {
                depthSquare++;
            } else if (ch === "]") {
                depthSquare--;
            } else if (ch === delimiter && depthCurly === 0 && depthSquare === 0) {
                result.push(input.slice(startIndex, i));
                startIndex = i + 1;
            }
        }
    }
    result.push(input.slice(startIndex));
    return result;
}

/**
 * Stringify a value into ESON format.
 * @param {any} value
 * @returns {string}
 */
function stringifyValue(value: any): string {
    if (value === null) {
        return "null";
    } else if (typeof value === "boolean") {
        return value ? "true" : "false";
    } else if (typeof value === "number") {
        return String(value);
    } else if (typeof value === "string") {
        // Use single quotes if string has spaces or special chars
        if (/\s|["'=]/.test(value) || value === "") {
            return `'${value.replace(/'/g, "\\'")}'`;
        }
        return value;
    } else if (Array.isArray(value)) {
        return stringifyArray(value);
    } else if (typeof value === "object") {
        // Nested object
        return ESON.stringify(value);
    }
    return "";
}

/**
 * Stringify an array into ESON format, e.g. [1,2,'text'].
 * @param {Array} arr
 * @returns {string}
 */
function stringifyArray(arr: any[]): string {
    const content = arr.map((item: any) => stringifyValue(item)).join(",");
    return `[${content}]`;
}

// Export the ESON object if needed (for Node.js CommonJS style)
// module.exports = ESON;

// Sample usage in a browser or Node.js
// const parsed = ESON.parse("{str=string,num=1234,bool=true,null=null,arr=[1,2,3],nest={nested='quote'}}");
// console.log(parsed);
// console.log(ESON.stringify(parsed));

export default ESON;
