execute as @s positioned ~0~~ run gametest run commander_api:setSlot
execute as @s positioned ~8~~ run gametest run commander_api:setitem
execute as @s positioned ~16~~ run gametest run commander_api:run
execute as @s positioned ~24~~ run gametest run commander_api:resetName
execute as @s positioned ~32~~ run gametest run commander_api:rename
execute as @s positioned ~40~~ run gametest run commander_api:projectileHit
execute as @s positioned ~48~~ run gametest run commander_api:knockback
execute as @s positioned ~56~~ run gametest run commander_api:kill
execute as @s positioned ~64~~ run gametest run commander_api:join
execute as @s positioned ~72~~ run gametest run commander_api:itemUseOn
execute as @s positioned ~80~~ run gametest run commander_api:itemUse
execute as @s positioned ~88~~ run gametest run commander_api:entityHurt
execute as @s positioned ~96~~ run gametest run commander_api:entityHit
execute as @s positioned ~104~~ run gametest run commander_api:entityDie
execute as @s positioned ~120~~ run gametest run commander_api:buttonPush
execute as @s positioned ~128~~ run gametest run commander_api:blockPlace
execute as @s positioned ~136~~ run gametest run commander_api:blockBreak
execute as @s positioned ~144~~ run gametest run commander_api:beforeChat