name: Notify to Dicsord

on:
    push:
      branches:
        - stable

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Notify to Discord
              run: |
                  curl -H "Content-Type: application/json" \
                  -X POST \
                  -d '{
                      "content": "test"
                  }' \
                  ${{ secrets.DISCORD_RELEASE_WEBHOOK }}
