name: Rename Release Asset

on:
    release:
        types: [created]

jobs:
    rename:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "14"

            - name: Install dependencies
              run: npm install axios

            - name: Rename asset
              run: node rename_asset.js
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
