name: Upload Release Asset

on:
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install zip
              run: sudo apt-get install zip

            - name: Zip the code
              run: zip -r source_code.zip .

            - name: Rename the file
              run: |
                  REPO_NAME=$(echo ${{ github.repository }} | cut -d '/' -f 2)
                  FILE_NAME=$REPO_NAME-${{ github.event.release.tag_name }}.mcpack
                  mv source_code.zip $FILE_NAME

            - name: Upload Release Asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: ./$(echo ${{ github.repository }} | cut -d '/' -f 2)-${{ github.event.release.tag_name }}.mcpack
                  asset_name: $(echo ${{ github.repository }} | cut -d '/' -f 2)-${{ github.event.release.tag_name }}.mcpack
                  asset_content_type: application/octet-stream
