name: Upload Release Asset

on:
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install rename
              run: sudo apt-get install rename

            - name: Rename asset
              run: |
                  mv your_asset.zip ${{ github.repository }}-${{ github.event.release.tag_name }}.zip
                  rename 's/\.zip$/.mcpack/' ${{ github.repository }}-${{ github.event.release.tag_name }}.zip

            - name: Upload Release Asset
              id: upload_release_asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: ./${{ github.repository }}-${{ github.event.release.tag_name }}.mcpack
                  asset_name: ${{ github.repository }}-${{ github.event.release.tag_name }}.mcpack
                  asset_content_type: application/octet-stream
