name: Upload Release Asset

on:
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install rename and jq
              run: sudo apt-get install rename jq

            - name: Get asset name
              id: get_asset
              run: |
                  ASSET_JSON=$(curl --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' "https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets")
                  ASSET_NAME=$(echo $ASSET_JSON | jq -r '.[0].name')
                  echo "::set-output name=asset_name::$ASSET_NAME"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Rename asset
              run: |
                  rename 's/\.zip$/.mcpack/' ${{ github.repository }}-${{ github.event.release.tag_name }}.zip

            - name: Upload Release Asset
              id: upload_release_asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: ./${{ github.repository }}-${{ github.event.release.tag_name }}.mcpack
                  asset_name: ${{ github.repository }}-${{ github.event.release.tag_name }}.mcpack
                  asset_content_type: application/octet-stream
